{{- if and .Values.istio.enabled .Values.observability.otelCollector.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-langfuse-no-mtls
spec:
  host: {{ .Release.Name }}-langfuse.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
