{{- if .Values.observability.otelCollector.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-otel-collector
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  selector:
    matchLabels:
      {{- include "audittrace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      labels:
        {{- include "audittrace.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.observability.otelCollector.image.repository }}:{{ .Values.observability.otelCollector.image.tag }}"
          args:
            - "--config=/etc/otel/otel-collector-config.yaml"
          ports:
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: prometheus
              containerPort: 8889
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/otel
              readOnly: true
          resources:
            {{- toYaml .Values.observability.otelCollector.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-otel-collector-config
{{- end }}
