{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}-external-observability
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
spec:
  hosts:
    - observability-external.{{ .Release.Namespace }}.svc.cluster.local
  location: MESH_EXTERNAL
  ports:
    - number: {{ .Values.observability.external.langfusePort }}
      name: http-langfuse
      protocol: HTTP
    - number: {{ .Values.observability.external.prometheusPort }}
      name: http-prometheus
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: {{ .Values.observability.external.langfuseIP }}
    - address: {{ .Values.observability.external.prometheusIP }}
{{- end }}
