{{- if .Values.istio.enabled }}
{{- $ns := .Release.Namespace }}
{{- $rel := .Release.Name }}
{{- $components := list "llm-chat" "llm-embed" "llm-summarizer" }}
{{- if and .Values.externalLLM.enabled .Values.externalLLM.mistral.enabled }}
{{- $components = append $components "llm-mistral" }}
{{- end }}
{{- range $components }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $rel }}-{{ . }}-no-mtls
spec:
  host: {{ $rel }}-{{ . }}.{{ $ns }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
{{- end }}
