{{- if .Values.istio.enabled }}
{{- $ns := .Release.Namespace }}
{{- $rel := .Release.Name }}
{{- range list "llm-chat" "llm-embed" "llm-summarizer" }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $rel }}-{{ . }}-no-mtls
spec:
  host: {{ $rel }}-{{ . }}.{{ $ns }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
{{- end }}
