apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-llm-embed
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-embed
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.externalLLM.embed.port }}
      targetPort: {{ .Values.externalLLM.embed.port }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-llm-embed
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.externalLLM.hostIP }}
    ports:
      - port: {{ .Values.externalLLM.embed.port }}
        protocol: TCP
        name: http
