{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-rabbitmq-topology
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq-topology
{{- end }}
