"""OpenAPI drift snapshot.

Pin the FastAPI-generated OpenAPI spec so route additions,
``response_model`` changes, and Pydantic-model edits surface as test
failures instead of silently drifting away from the vendored
``docs/reference/audittrace/openapi.yaml`` spec that external clients
consume.

To accept an intentional change:

    OPENAPI_SNAPSHOT_UPDATE=1 pytest tests/test_openapi_drift.py

That re-runs the test, overwrites the snapshot AND the vendored spec,
and leaves the diff in git so the reviewer sees exactly what changed.
The Make target ``make openapi-export`` is the user-facing wrapper.

Why a snapshot: the spec is generated by FastAPI from runtime
introspection of route decorators + Pydantic model field types. Any
"hand-written" spec would drift; locking to ``app.openapi()`` output
makes the runtime the source of truth, and the snapshot captures
"this is what we shipped." Same shape as the
``tests/test_docs_drift.py`` AGENTS.md guard from v1.0.8 — proven
pattern.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).parent.parent
SNAPSHOT_PATH = REPO_ROOT / "tests" / "fixtures" / "openapi.snapshot.yaml"
VENDORED_PATH = REPO_ROOT / "docs" / "reference" / "audittrace" / "openapi.yaml"

VENDORED_HEADER = (
    "# Generated by AuditTrace-AI from FastAPI's app.openapi() — DO NOT\n"
    "# hand-edit. Regenerate with: ``make openapi-export`` (which reruns\n"
    "# tests/test_openapi_drift.py with OPENAPI_SNAPSHOT_UPDATE=1).\n"
    "#\n"
    "# This file is the contract external clients (LibreChat fork,\n"
    "# audittrace-webui, OpenCode bridge) consume. The runtime spec\n"
    "# at GET /openapi.json must always match this file; the test\n"
    "# tests/test_openapi_drift.py is the gate.\n"
)


def _normalised_spec() -> dict[str, Any]:
    """Return the live FastAPI spec, normalised so cosmetic changes
    (dict ordering, runtime version-bumps) don't trip the snapshot."""
    # Importing inside the function so the test isolates each call;
    # the create_app() side-effects (logging setup) won't run twice.
    from audittrace.server import create_app

    app = create_app()
    spec: dict[str, Any] = app.openapi()

    # Remove the ``info.version`` so a release bump doesn't churn the
    # snapshot. The version is an artefact of the build, not part of
    # the API contract that the snapshot is pinning.
    info = spec.get("info") or {}
    info.pop("version", None)
    return spec


def _ordered_yaml_dump(data: dict[str, Any]) -> str:
    """Stable YAML representation: sort keys at every level so the
    snapshot is deterministic across Python builds."""
    return yaml.safe_dump(
        data,
        sort_keys=True,
        default_flow_style=False,
        width=120,
        allow_unicode=True,
    )


def test_openapi_snapshot_matches() -> None:
    """The FastAPI-rendered OpenAPI spec must match the committed
    snapshot. To accept a deliberate change, run:

        OPENAPI_SNAPSHOT_UPDATE=1 pytest tests/test_openapi_drift.py
    """
    live = _normalised_spec()
    live_yaml = _ordered_yaml_dump(live)

    if os.environ.get("OPENAPI_SNAPSHOT_UPDATE") == "1":
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(live_yaml, encoding="utf-8")
        VENDORED_PATH.parent.mkdir(parents=True, exist_ok=True)
        VENDORED_PATH.write_text(VENDORED_HEADER + live_yaml, encoding="utf-8")
        # When updating, still pass the test (regenerated == live).
        return

    assert SNAPSHOT_PATH.exists(), (
        f"Snapshot missing at {SNAPSHOT_PATH}. Generate it with: "
        "OPENAPI_SNAPSHOT_UPDATE=1 pytest tests/test_openapi_drift.py"
    )
    saved = SNAPSHOT_PATH.read_text(encoding="utf-8")

    if saved != live_yaml:
        # Render a compact diff in the assertion message so the
        # reviewer sees what changed without leaving the test output.
        import difflib

        diff = "\n".join(
            difflib.unified_diff(
                saved.splitlines(),
                live_yaml.splitlines(),
                fromfile="snapshot",
                tofile="live",
                lineterm="",
            )
        )[:5000]
        msg = (
            f"OpenAPI spec drifted from {SNAPSHOT_PATH.name}.\n"
            "If this change is intentional, accept it with:\n"
            "    OPENAPI_SNAPSHOT_UPDATE=1 pytest tests/test_openapi_drift.py\n"
            "Then commit the snapshot + the regenerated vendored spec.\n\n"
            f"Diff (truncated to 5000 chars):\n{diff}"
        )
        raise AssertionError(msg)


def test_vendored_spec_matches_snapshot() -> None:
    """The vendored spec under ``docs/reference/audittrace/openapi.yaml``
    is the contract external clients consume. It must equal the
    snapshot (modulo the header comment) so a contributor can't update
    one without the other.
    """
    if not VENDORED_PATH.exists():
        # If the vendored spec doesn't exist yet, instruct the user to
        # generate it.
        raise AssertionError(
            f"Vendored spec missing at {VENDORED_PATH}. Generate with: "
            "OPENAPI_SNAPSHOT_UPDATE=1 pytest tests/test_openapi_drift.py"
        )

    saved = SNAPSHOT_PATH.read_text(encoding="utf-8")
    vendored = VENDORED_PATH.read_text(encoding="utf-8")
    # Strip the header comment block from the vendored file (lines
    # starting with ``#``) before comparing.
    vendored_body = "\n".join(
        line for line in vendored.splitlines() if not line.startswith("#")
    ).lstrip("\n")
    if vendored_body != saved.rstrip("\n"):
        raise AssertionError(
            f"{VENDORED_PATH.name} is out of sync with {SNAPSHOT_PATH.name}. "
            "Regenerate with: OPENAPI_SNAPSHOT_UPDATE=1 pytest "
            "tests/test_openapi_drift.py"
        )


def test_critical_paths_present() -> None:
    """Sanity check: a few load-bearing routes must appear in the live
    spec. Catches accidental router-include removal earlier than the
    snapshot diff would."""
    spec = _normalised_spec()
    paths = spec.get("paths") or {}
    required = [
        "/v1/chat/completions",
        "/health",
        "/interactions",
        "/sessions",
        "/memory/conversational",
        "/memory/conversational/{session_id}",
        "/session/save",
        "/session/summary",
        "/context",
    ]
    missing = [p for p in required if p not in paths]
    assert not missing, (
        f"Critical OpenAPI paths missing: {missing}. "
        f"Live spec has {len(paths)} paths total."
    )


def test_metadata_is_current() -> None:
    """Title and description must reflect the current AuditTrace-AI
    framing — guards against the v1.0.10 drift class (where title
    stayed 'Sovereign Memory Server' through three releases)."""
    spec = _normalised_spec()
    info = spec.get("info") or {}
    assert info.get("title") == "AuditTrace-AI", (
        f"OpenAPI title is {info.get('title')!r}; expected 'AuditTrace-AI'. "
        "Update create_app() in src/audittrace/server.py."
    )
    description = info.get("description") or ""
    assert "EU-AI-Act" in description or "audit trail" in description.lower(), (
        "OpenAPI description should mention the EU AI Act / audit trail "
        "framing per the v1.0.10 metadata refresh."
    )
    # tags array (with descriptions) must be present
    tags = spec.get("tags") or []
    assert len(tags) >= 6, f"expected >=6 tag groups, got {len(tags)}"


# Suppress unused-import lint when ``json`` isn't used directly above
# (kept for ad-hoc debugging during snapshot regeneration).
_ = json
