apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memory-server
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: memory-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.memoryServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "audittrace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memory-server
