{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-secret
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.keycloak.adminPassword | quote }}
{{- end }}
