{{- if .Values.secrets.chromadb.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chromadb-secret
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.secrets.chromadb.token | quote }}
{{- end }}
