#!/usr/bin/env bash
# Bootstrap Langfuse as sibling compose stack (ADR-021.2)
# Langfuse runs on the shared audittrace-net but with its own Postgres.
set -euo pipefail

LANGFUSE_DIR="${1:-../langfuse}"

echo "Creating shared Docker network..."
docker network create audittrace-net 2>/dev/null || echo "Network audittrace-net already exists"

echo "Setting up Langfuse in ${LANGFUSE_DIR}..."
mkdir -p "${LANGFUSE_DIR}"
cd "${LANGFUSE_DIR}"

if [ ! -f docker-compose.yml ]; then
    echo "Downloading official Langfuse docker-compose.yml..."
    curl -fsSL https://raw.githubusercontent.com/langfuse/langfuse/main/docker-compose.yml \
        -o docker-compose.yml
else
    echo "docker-compose.yml already exists (skipped)"
fi

# Attach Langfuse to the shared network via override file so upstream
# compose is never edited by hand, AND force Next.js standalone to
# bind to 0.0.0.0.
#
# HOSTNAME=0.0.0.0 — Next.js standalone reads HOSTNAME at startup
# and binds to whatever IP it resolves to. Docker sets HOSTNAME to
# the container ID, which resolves (via /etc/hosts) to a SINGLE IP
# on ONE of the container's networks. Since langfuse-web is attached
# to both `default` (langfuse_default) and `audittrace-net`, the
# default hostname resolution picks one interface and the other
# silently gets "connection refused" — from host curl AND from
# audittrace-ai's OTel exporter, even though the web app
# is running fine and logs "✓ Ready in 0ms". This was a full
# dogfood-session outage on 2026-04-11. Forcing HOSTNAME=0.0.0.0
# tells Next.js to bind to every interface, which is the correct
# behaviour for a multi-network container.
cat > docker-compose.override.yml <<'YAML'
# Auto-generated by audittrace-ai/scripts/setup-langfuse.sh
# See that script for the rationale behind HOSTNAME=0.0.0.0.
services:
  langfuse-web:
    networks: [default, audittrace-net]
    environment:
      HOSTNAME: 0.0.0.0
networks:
  audittrace-net:
    external: true
YAML

echo ""
echo "Langfuse configured at: ${LANGFUSE_DIR}"
echo "Start with: cd ${LANGFUSE_DIR} && docker compose up -d"
echo "Upgrade with: cd ${LANGFUSE_DIR} && docker compose pull && docker compose up -d"
echo ""
echo "OTLP endpoint: http://langfuse-web:3000/api/public/otel"
echo "Set AUDITTRACE_OTLP_ENDPOINT in your .env to activate trace export."
