{{- if .Values.reaper.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pod-reaper
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: pod-reaper
{{- end }}
