{{- if and .Values.console.enabled .Values.console.bff.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.console.bff.serviceAccount.name }}
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: librechat-bff
{{- end }}
