{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-allow-memory
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: memory-server
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
      to:
        - operation:
            ports: ["{{ .Values.memoryServer.port }}"]
{{- end }}
