{{- if and .Values.istio.enabled .Values.istio.defaultDenyAll }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-deny-all
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
spec:
  {}
{{- end }}
