{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Release.Name }}-default
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
