{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    {{- include "audittrace.labels" . | nindent 4 }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.istio.gateway.name }}
  http:
    - match:
        - uri:
            prefix: /realms
      route:
        - destination:
            host: {{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /admin
      route:
        - destination:
            host: {{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
{{- end }}
